Repository radroid/Hangman, pull requests merged in 2020-07, with the labels that each got.

#1 Update readme
  README.md
Labels: documentation

#2 Update README.md
  README.md
Labels: documentation

#3 Update for Simple Hangman
  Hangman.py
  Package/tests/test_HangmanGame.py
  PlayHangman.py
  package/__init__.py
  package/hangman_pack/HangmanGame.py
  package/hangman_pack/__init__.py
  package/setup.py
  package/tests/__init__.py
  package/tests/test_HangmanGame.py
Labels: enhancement

#6 Improve Word Bank
  Hangman/HangmanGame.py
  Hangman/__init__.py
  PlayHangman.py
  __init__.py
  requirements.txt
  setup.py
  tests/test_HangmanGame.py
  word_bank.txt
Labels: enhancement

#12 Update python-package.yml
  .github/workflows/python-package.yml
Labels: workflow

#13 Refactoring code
  Hangman/HangmanGame.py
  Hangman/__init__.py
  PlayHangman.py
  hangman/HangmanGame.py
  hangman/__init__.py
  hangman/data/word_bank.txt
  hangman/examples/PlayHangman.py
  hangman/examples/PlaySimpleHangman.py
  requirements.txt
  setup.py
  tests/__init__.py
  tests/test_HangmanGame.py
  tox.ini
Labels: documentation, enhancement
